#!/usr/bin/env python3
"""Build production assets and static country entry pages for JOURNEY ATLAS."""

from __future__ import annotations

import base64
import html
import json
import os
from pathlib import Path
from urllib.parse import urljoin

ROOT = Path(__file__).resolve().parents[1]
SITE_URL = os.environ.get("JOURNEY_ATLAS_SITE_URL", "https://yagenji.github.io/Journey-Atlas/").rstrip("/") + "/"

COUNTRY_CSS_SOURCES = [
    "assets/css/style.css",
    "assets/css/atlas-overrides.css",
    "assets/css/country-fixes.css",
    "assets/css/country-layout-final.css",
    "assets/css/country-atlas-depth.css",
    "assets/css/country-polish.css",
    "assets/css/country-refine.css",
    "assets/css/country-template-v2.css",
    "assets/css/country-icon-system.css",
    "assets/css/country-trivia.css",
    "assets/css/site-unify.css",
    "assets/css/site-footer.css",
]

TOP_CSS_SOURCES = [
    "assets/css/top-preview.css",
    "assets/css/top-layout-v3.css",
    "assets/css/top-layout-v4.css",
    "assets/css/map-regions.css",
    "assets/css/top-scope.css",
    "assets/css/site-unify.css",
    "assets/css/site-footer.css",
]

TOP_CSS_LINKS = [
    '<link rel="stylesheet" href="assets/css/top-preview.css">',
    '<link rel="stylesheet" href="assets/css/top-layout-v3.css">',
    '<link rel="stylesheet" href="assets/css/top-layout-v4.css?v=20260822-2134">',
    '<link rel="stylesheet" href="assets/css/map-regions.css?v=20260822-2346">',
    '<link rel="stylesheet" href="assets/css/top-scope.css?v=20260825-0152">',
    '<link rel="stylesheet" href="assets/css/site-unify.css?v=20260825-0210">',
    '<link rel="stylesheet" href="assets/css/site-footer.css?v=20260824-1328">',
]


def bundle_css(output: str, sources: list[str]) -> None:
    sections = ["/* Generated by scripts/build_site.py. Do not edit this production bundle directly. */\n"]
    for source in sources:
        path = ROOT / source
        if not path.exists():
            raise FileNotFoundError(f"CSS source missing: {source}")
        sections.append(f"\n/* ===== {source} ===== */\n")
        sections.append(path.read_text(encoding="utf-8"))
        sections.append("\n")
    (ROOT / output).write_text("".join(sections), encoding="utf-8")


def extension_for_mime(mime: str) -> str:
    return {
        "image/webp": ".webp",
        "image/avif": ".avif",
        "image/png": ".png",
        "image/jpeg": ".jpg",
    }.get(mime, ".bin")


def materialize_encoded_asset(source: str) -> str:
    source_path = ROOT / source
    if source.endswith(".parts.json"):
        manifest = json.loads(source_path.read_text(encoding="utf-8"))
        parts = manifest.get("parts") or []
        if not parts:
            raise ValueError(f"No parts in manifest: {source}")
        encoded = "".join((ROOT / part).read_text(encoding="utf-8").strip() for part in parts)
        encoded = "".join(encoded.split())
        signature = manifest.get("signature")
        if signature and not encoded.startswith(signature):
            raise ValueError(f"Signature mismatch: {source}")
        binary = base64.b64decode(encoded, validate=True)
        suffix = extension_for_mime(manifest.get("mime", "application/octet-stream"))
        output_path = source_path.with_name(source_path.name.removesuffix(".parts.json") + suffix)
        output_path.write_bytes(binary)
        return output_path.relative_to(ROOT).as_posix()

    if source.endswith(".b64"):
        encoded = "".join(source_path.read_text(encoding="utf-8").split())
        binary = base64.b64decode(encoded, validate=True)
        output_path = source_path.with_suffix("")
        output_path.write_bytes(binary)
        return output_path.relative_to(ROOT).as_posix()

    return source


def rewrite_encoded_assets(value):
    if isinstance(value, dict):
        return {key: rewrite_encoded_assets(item) for key, item in value.items()}
    if isinstance(value, list):
        return [rewrite_encoded_assets(item) for item in value]
    if isinstance(value, str) and (value.endswith(".parts.json") or value.endswith(".b64")):
        return materialize_encoded_asset(value)
    return value


def load_registry() -> dict:
    return json.loads((ROOT / "data/atlas-destinations.json").read_text(encoding="utf-8"))


def published_destinations(registry: dict) -> list[dict]:
    return [item for item in registry.get("destinations", []) if item.get("atlasPublished")]


def set_tag(text: str, old: str, new: str) -> str:
    if old not in text:
        raise ValueError(f"Template marker missing: {old}")
    return text.replace(old, new, 1)


def prepare_top_page() -> None:
    path = ROOT / "index.html"
    page = path.read_text(encoding="utf-8")
    for link in TOP_CSS_LINKS:
        page = page.replace(f"  {link}\n", "")
    marker = '  <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&family=Shippori+Mincho:wght@400;500;600&family=Zen+Kaku+Gothic+New:wght@400;500;700&display=swap" rel="stylesheet">\n'
    if 'assets/css/top.css' not in page:
        page = page.replace(marker, marker + '  <link rel="stylesheet" href="assets/css/top.css?v=20260825-1027">\n', 1)

    canonical = SITE_URL
    if 'rel="canonical"' not in page:
        page = page.replace('  <title>JOURNEY ATLAS</title>\n', f'  <title>JOURNEY ATLAS</title>\n  <link rel="canonical" href="{canonical}">\n  <meta property="og:type" content="website">\n  <meta property="og:site_name" content="JOURNEY ATLAS">\n  <meta property="og:title" content="JOURNEY ATLAS">\n  <meta property="og:description" content="201の国・地域をイラストと地図でめぐり、次に行きたい場所を見つけるビジュアル図鑑、JOURNEY ATLAS。">\n  <meta property="og:url" content="{canonical}">\n  <meta property="og:image" content="{urljoin(SITE_URL, "assets/images/top/hero-world-collage.svg")}">\n  <meta name="twitter:card" content="summary_large_image">\n', 1)

    page = page.replace('<img id="hero-image" ', '<img id="hero-image" fetchpriority="high" ', 1)
    page = page.replace('class="lens-card__art"><img ', 'class="lens-card__art"><img loading="lazy" decoding="async" ', 1)
    path.write_text(page, encoding="utf-8")


def prepare_generic_country_page() -> None:
    path = ROOT / "country.html"
    page = path.read_text(encoding="utf-8")
    if 'name="robots"' not in page:
        page = page.replace('  <meta name="description" id="meta-description"', '  <meta name="robots" content="noindex,follow">\n  <meta name="description" id="meta-description"', 1)
    path.write_text(page, encoding="utf-8")


def generate_country_page(destination: dict) -> str:
    slug = destination["slug"]
    data_path = ROOT / f"data/countries/{slug}.json"
    if not data_path.exists():
        raise FileNotFoundError(f"Published country data missing: {data_path}")

    data = json.loads(data_path.read_text(encoding="utf-8"))
    data = rewrite_encoded_assets(data)
    data_path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    template = (ROOT / "country.html").read_text(encoding="utf-8")
    title = f"{data['nameJa']} | {data['nameEn']} — JOURNEY ATLAS"
    description = data.get("seo", {}).get("description") or data.get("hero", {}).get("lead") or f"{data['nameJa']}を景色と地図からめぐるJOURNEY ATLAS。"
    canonical = urljoin(SITE_URL, f"countries/{slug}/")
    hero = data.get("seo", {}).get("ogImage") or data.get("hero", {}).get("image", "")
    og_image = urljoin(SITE_URL, hero) if hero else urljoin(SITE_URL, "assets/icons/favicon.svg")

    page = template
    page = set_tag(page, '<html lang="ja">', f'<html lang="ja" data-country="{html.escape(slug)}">')
    page = set_tag(page, '<head>', '<head>\n  <base href="../../">')
    page = set_tag(page, '<title>JOURNEY ATLAS — Country</title>', f'<title>{html.escape(title)}</title>')
    page = set_tag(page, 'content="景色と地図から、次の旅先に出会う。JOURNEY ATLASの国ページ。"', f'content="{html.escape(description, quote=True)}"')
    page = set_tag(page, 'href="https://yagenji.github.io/Journey-Atlas/country.html"', f'href="{html.escape(canonical, quote=True)}"')
    page = set_tag(page, 'content="JOURNEY ATLAS — Country"', f'content="{html.escape(title, quote=True)}"')
    page = set_tag(page, 'content="景色と地図から、次の旅先に出会う。JOURNEY ATLASの国ページ。"', f'content="{html.escape(description, quote=True)}"')
    page = set_tag(page, 'content="https://yagenji.github.io/Journey-Atlas/country.html"', f'content="{html.escape(canonical, quote=True)}"')
    page = set_tag(page, 'content="https://yagenji.github.io/Journey-Atlas/assets/icons/favicon.svg"', f'content="{html.escape(og_image, quote=True)}"')
    page = page.replace('<meta name="robots" content="noindex,follow">', '<meta name="robots" content="index,follow">', 1)

    output = ROOT / "countries" / slug / "index.html"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(page, encoding="utf-8")
    return canonical


def rewrite_published_hrefs(registry: dict) -> None:
    for item in registry.get("destinations", []):
        if item.get("atlasPublished") and item.get("slug"):
            item["href"] = f"countries/{item['slug']}/"
    (ROOT / "data/atlas-destinations.json").write_text(json.dumps(registry, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def generate_sitemap(country_urls: list[str]) -> None:
    urls = [SITE_URL, *country_urls]
    body = "\n".join(f"  <url><loc>{html.escape(url)}</loc></url>" for url in urls)
    xml = f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{body}\n</urlset>\n'
    (ROOT / "sitemap.xml").write_text(xml, encoding="utf-8")
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {urljoin(SITE_URL, 'sitemap.xml')}\n", encoding="utf-8")


def main() -> int:
    bundle_css("assets/css/country.css", COUNTRY_CSS_SOURCES)
    bundle_css("assets/css/top.css", TOP_CSS_SOURCES)
    prepare_top_page()
    prepare_generic_country_page()
    registry = load_registry()
    destinations = published_destinations(registry)
    urls = [generate_country_page(item) for item in destinations]
    rewrite_published_hrefs(registry)
    generate_sitemap(urls)
    print(f"Built CSS bundles and {len(urls)} static country page(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
